# Generated by Django 4.1.3 on 2022-11-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='enter your username', max_length=30)),
                ('password', models.CharField(help_text='enter your password', max_length=30)),
            ],
        ),
    ]
